### ISSUE TITLE
Remove "Check out new print view" message

### ISSUE THREAD

**Issue by mchelen** [TimDaub/jsonresume-theme-paper#1]
Is there a reason to keep this message at the beginning of the page? It may be helpful for new users, but when sharing a resume link such as http://registry.jsonresume.org/thomasdavis?theme=paper with an employer, it looks unprofessional.

**Comment by nihey** [comment]
https://github.com/TimDaub/jsonresume-theme-paper/pull/3 This pull request should do the trick.

**Comment by TimDaub** [comment]
Merged.
