### ISSUE TITLE
Please publish latest version

### ISSUE THREAD

**Issue by nicholascapo** [TimDaub/jsonresume-theme-paper#24]
Please publish the latest version to npm.

**Comment by TimDaub** [comment]
Hey @nicholascapo, thanks for pointing that out. I just released v0.4.0 on npm and as a git tag.

**Comment by nicholascapo** [comment]
Thanks! :100:

**Comment by nicholascapo** [comment]
I think your branch was old when you published. :thinking:

Tag `v0.4.0` points to 1eeb163adb74acbc2d291b4de12dc3b23e24360b, which isn't a commit in `master`, but it's parent is dd41453281c7c4442ee58f58afd8154f0758546e which is also the commit right before my recently merged changes.

Would you mind pulling (and merging if necessary) and then publishing v0.5.0?

**Comment by TimDaub** [comment]
478fe83 should now be v0.5.0 on npm and GH.
Sorry for any inconvenience.

**Comment by nicholascapo** [comment]
Excellent! It working for me now!
